functionsDirectory = "C:\\Users\\keyga\\OneDrive\\Documents\\Development\\Github\\WrestlingClubofRuskin\\wrestling-club-of-ruskin\\netlify\\functions"
functionsDirectoryOrigin = "ui"
plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\keyga\\OneDrive\\Documents\\Development\\Github\\WrestlingClubofRuskin\\wrestling-club-of-ruskin\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\keyga\\OneDrive\\Documents\\Development\\Github\\WrestlingClubofRuskin\\wrestling-club-of-ruskin"
command = "npm run build"
functions = "C:\\Users\\keyga\\OneDrive\\Documents\\Development\\Github\\WrestlingClubofRuskin\\wrestling-club-of-ruskin\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]